<?php
/**
 * Copyright (C) 2018 Kunal Mehta <legoktm@member.fsf.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace MediaWiki\SecureLinkFixer;

use Maintenance;

$IP = getenv( 'MW_INSTALL_PATH' );
if ( $IP === false ) {
	$IP = __DIR__ . '/../../..';
}
require_once "$IP/maintenance/Maintenance.php";

/**
 * Downloads Mozilla's HSTS preload list and builds it into a CDB
 */
class FetchList extends Maintenance {
	public function __construct() {
		parent::__construct();
		$this->mDescription = 'Fetch HSTS preload list and build database';
	}

	public function execute() {
		// phpcs:ignore Generic.Files.LineLength
		$feedUrl = 'https://hg.mozilla.org/mozilla-central/atom-log/tip/security/manager/ssl/nsSTSPreloadList.inc';
		$feed = file_get_contents( $feedUrl );
		preg_match( '!"http://hg.mozilla.org/mozilla-central/rev/([a-f0-9]*?)"!', $feed, $matches );
		if ( !isset( $matches[1] ) ) {
			$this->fatalError( 'Unable to parse revision id for HSTS preload list' );
		}
		$rev = $matches[1];
		$this->output( "Downloading the HSTS preload list (revision $rev)..." );
		// phpcs:ignore Generic.Files.LineLength
		$url = "https://hg.mozilla.org/mozilla-central/raw-file/$rev/security/manager/ssl/nsSTSPreloadList.inc";
		$lines = explode( "\n", file_get_contents( $url ) );
		$this->output( "done\n" );
		$inList = false;
		$header = <<<HEADER
Generated by fetchList.php using mozilla-central@$rev
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
phpcs:ignoreFile
HEADER;

		// XXX: Should we care about gPreloadListExpirationTime?
		$data = [];
		foreach ( $lines as $line ) {
			if ( $line === '%%' ) {
				$inList = !$inList;
				continue;
			}

			if ( $inList ) {
				$exploded = explode( ', ', $line );
				$data[$exploded[0]] = (int)$exploded[1];
			}
		}
		$code = wfMakeStaticArrayFile( $data, $header );
		file_put_contents( __DIR__ . '/../domains.php', $code );
		$this->output( "Updated domains.php\n" );
	}
}

$maintClass = FetchList::class;
require_once RUN_MAINTENANCE_IF_MAIN;
