<?php
/**
 * Copyright (C) 2018 Kunal Mehta <legoktm@member.fsf.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace MediaWiki\SecureLinkFixer;

use Wikimedia\StaticArrayWriter;

$IP = getenv( 'MW_INSTALL_PATH' );
if ( $IP === false ) {
	$IP = __DIR__ . '/../../..';
}

require_once "$IP/includes/libs/StaticArrayWriter.php";

/**
 * Downloads Mozilla's HSTS preload list and builds it into a PHP file.
 *
 * We explicitly don't use Maintenance here so that this script
 * can be run without needing all of MediaWiki to be installed.
 */
function main() {
	// phpcs:ignore Generic.Files.LineLength
	$feedUrl = 'https://hg.mozilla.org/mozilla-central/atom-log/tip/security/manager/ssl/nsSTSPreloadList.inc';
	$feed = file_get_contents( $feedUrl );
	preg_match( '!"https://hg.mozilla.org/mozilla-central/rev/([a-f0-9]*?)"!', $feed, $matches );
	preg_match( '!<updated>(.*?)</updated>!', $feed, $updated );
	if ( !isset( $matches[1] ) || !isset( $updated[1] ) ) {
		echo "Unable to parse revision id/updated date for HSTS preload list\n";
		die( 1 );
	}
	$rev = $matches[1];
	$date = substr( $updated[1], 0, 10 );
	echo "Downloading the HSTS preload list (revision $rev)...";
	// phpcs:ignore Generic.Files.LineLength
	$url = "https://hg.mozilla.org/mozilla-central/raw-file/$rev/security/manager/ssl/nsSTSPreloadList.inc";
	$lines = explode( "\n", file_get_contents( $url ) );
	echo "done\n";
	$inList = false;
	$header = <<<HEADER
Generated by fetchList.php using mozilla-central@$rev ($date)
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
phpcs:ignoreFile
HEADER;

	// XXX: Should we care about gPreloadListExpirationTime?
	$data = [];
	foreach ( $lines as $line ) {
		if ( $line === '%%' ) {
			$inList = !$inList;
			continue;
		}

		if ( $inList ) {
			$exploded = explode( ', ', $line );
			$data[$exploded[0]] = (int)$exploded[1];
		}
	}
	$writer = new StaticArrayWriter();
	$code = $writer->create( $data, $header );
	file_put_contents( __DIR__ . '/../domains.php', $code );
	echo "Updated domains.php\n";
}

main();
